Fix for creating L/AS/PMS dir.
Added if clause on Library/Application Support dir, and that user can create this.

diff --git a/redhat/files/etc/rc.d/init.d/plexmediaserver b/redhat/files/etc/rc.d/init.d/plexmediaserver
--- a/redhat/files/etc/rc.d/init.d/plexmediaserver
+++ b/redhat/files/etc/rc.d/init.d/plexmediaserver
@@ -26,7 +26,15 @@ start()
 {
         [ $UID -eq 0 ] || exit 4
         [ -x "$PLEX_MEDIA_SERVER_HOME/$PMS_BIN" ] || exit 5
-        [ -f "$config" ] || exit 6 
+        [ -f "$config" ] || exit 6
+        if [ ! -f "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR" ];
+        then
+         su -s /bin/sh plex -c 'mkdir -p "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR" > /dev/null 2>&1'
+         if [ ! $? -eq 0 ]; then
+          echo "WARNING COULDN'T CREATE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+          exit 1
+         fi
+        fi
         echo -n $"Starting $prog: "
         su -s /bin/sh plex -c ". $config; cd $PLEX_MEDIA_SERVER_HOME; ./'$PMS_BIN'"&
         sleep 3
